server:
  port: 80

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
       id: service-hosp
       uri: lb://service-hosp
       predicates: Path=/*/hosp/**

      routes[1]:
       id: service-dict
       uri: lb://service-dict
       predicates: Path=/*/dict/**
      routes[2]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/user/**
      routes[3]:
        id: service-msm
        uri: lb://service-msm
        predicates: Path=/*/msm/**
      routes[4]:
        id: service-oss
        uri: lb://service-oss
        predicates: Path=/*/oss/**



